### ISSUE TITLE
HubSpot API key - no logner supported 

### ISSUE THREAD

**Issue by dulajo** [goforboom/hubspot#4]
Auth via simple api key in the queryParam `hapiKey` will no longer be supported 
![image](https://user-images.githubusercontent.com/60926165/198961443-1b93f1a2-a823-47c2-a25c-cbd755a58e35.png)

all types of auth -> https://developers.hubspot.com/docs/api/intro-to-auth

Migration to private apps -> https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app?_ga=2.219255578.2015489188.1667203677-150736044.1665476086

**Comment by sitole** [comment]
@DejfCold can we please create relict task and describe next steps? Thanks!

**Comment by DejfCold** [comment]
Ooops, I created feature task. Oh well, next time I guess.

**Comment by sitole** [comment]
Released 🚀 https://repo1.maven.org/maven2/com/goforboom/hubspot-sdk/1.2.0/
